import { Channel, Streaming } from "@/entities/channel";
import { User } from "@/entities/user";

const users = [
  {
    id: 1,
    avatar: "",
    bio: "This is my bio",
    username: "MrBeast",
    email: "beast123@gmail.com",
    phoneNumber: "",
    password: "",
    blockedUsers: [],
    location: "",
    createdDate: new Date(),
    linkAccount: "",
    followers: [2, 3],
    followings: [],
    backgroundPicture: "",
  },
  {
    id: 2,
    avatar: "https://example.com/avatar2.jpg",
    bio: "Adventure seeker and nature lover. Living life to the fullest!",
    username: "NatureExplorer",
    email: "nature@example.com",
    phoneNumber: "+9876543210",
    password: "hashed_password_2",
    blockedUsers: [1],
    location: "Wilderness City, USA",
    createdDate: new Date(),
    linkAccount: "https://instagram.com/natureexplorer",
    followers: [1, 3, 4],
    followings: [5],
    backgroundPicture: "https://example.com/background2.jpg",
  },
  {
    id: 3,
    avatar: "https://example.com/avatar3.jpg",
    bio: "Passionate about technology and coding. Always learning!",
    username: "CodeGeek",
    email: "code@example.com",
    phoneNumber: "+1122334455",
    password: "hashed_password_3",
    blockedUsers: [],
    location: "TechHub City, USA",
    createdDate: new Date(),
    linkAccount: "https://github.com/codegeek",
    followers: [1, 2, 4],
    followings: [2],
    backgroundPicture: "https://example.com/background3.jpg",
  },
  {
    id: 4,
    avatar: "https://example.com/avatar4.jpg",
    bio: "Foodie and culinary explorer. Cooking is my passion!",
    username: "FoodExplorer",
    email: "food@example.com",
    phoneNumber: "+3344556677",
    password: "hashed_password_4",
    blockedUsers: [2],
    location: "Gourmet Town, USA",
    createdDate: new Date(),
    linkAccount: "https://twitter.com/foodexplorer",
    followers: [2, 3, 5],
    followings: [1],
    backgroundPicture: "https://example.com/background4.jpg",
  },
  {
    id: 5,
    avatar: "https://example.com/avatar5.jpg",
    bio: "Art enthusiast and creative mind. Expressing through colors!",
    username: "ArtisticSoul",
    email: "art@example.com",
    phoneNumber: "+9988776655",
    password: "hashed_password_5",
    blockedUsers: [],
    location: "Creative City, USA",
    createdDate: new Date(),
    linkAccount: "https://instagram.com/artisticsoul",
    followers: [1, 4],
    followings: [3],
    backgroundPicture: "https://example.com/background5.jpg",
  },
  {
    id: 6,
    avatar: "https://example.com/avatar6.jpg",
    bio: "Music lover and concert enthusiast. Always chasing the beat!",
    username: "MusicHarmony",
    email: "music@example.com",
    phoneNumber: "+7766554433",
    password: "hashed_password_6",
    blockedUsers: [3],
    location: "Melody City, USA",
    createdDate: new Date(),
    linkAccount: "https://soundcloud.com/musicharmony",
    followers: [1, 5],
    followings: [2, 4],
    backgroundPicture: "https://example.com/background6.jpg",
  },
  {
    id: 7,
    avatar: "https://example.com/avatar7.jpg",
    bio: "Fitness freak and health advocate. Embracing an active lifestyle!",
    username: "FitExplorer",
    email: "fitness@example.com",
    phoneNumber: "+1122337788",
    password: "hashed_password_7",
    blockedUsers: [],
    location: "Active City, USA",
    createdDate: new Date(),
    linkAccount: "https://fitbit.com/fitexplorer",
    followers: [2, 5],
    followings: [3, 6],
    backgroundPicture: "https://example.com/background7.jpg",
  },
  {
    id: 8,
    avatar: "https://example.com/avatar8.jpg",
    bio: "Bookworm and literature enthusiast. Diving into different worlds through words!",
    username: "BookWanderer",
    email: "books@example.com",
    phoneNumber: "+9988771100",
    password: "hashed_password_8",
    blockedUsers: [],
    location: "Readers' Haven, USA",
    createdDate: new Date(),
    linkAccount: "https://goodreads.com/bookwanderer",
    followers: [1, 4],
    followings: [5, 7],
    backgroundPicture: "https://example.com/background8.jpg",
  },
];

const streamings: Streaming[] = [
  {
    id: 1,
    ownerId: 1,
    viewers: 345,
    title: "Ace on day 27",
    chats: [],
    startedTime: new Date(),
    tags: ["English", "Troll"],
    category: "Troll VietNam",
  },
  {
    id: 2,
    ownerId: 2,
    viewers: 500,
    title: "Island Hopping Adventure",
    chats: [],
    startedTime: new Date(),
    tags: ["Travel", "Adventure"],
    category: "Travel Adventures",
  },
  {
    id: 3,
    ownerId: 3,
    viewers: 120,
    title: "Coding Marathon",
    chats: [],
    startedTime: new Date(),
    tags: ["Technology", "Coding"],
    category: "Tech Talks",
  },
  {
    id: 4,
    ownerId: 4,
    viewers: 1000,
    title: "Epic Gaming Night",
    chats: [],
    startedTime: new Date(),
    tags: ["Gaming", "Entertainment"],
    category: "Gaming Fun",
  },
  {
    id: 5,
    ownerId: 5,
    viewers: 345,
    title: "Ace on day 27",
    chats: [],
    startedTime: new Date(),
    tags: ["English", "Troll"],
    category: "Troll VietNam",
  },
  {
    id: 6,
    ownerId: 6,
    viewers: 500,
    title: "Island Hopping Adventure",
    chats: [],
    startedTime: new Date(),
    tags: ["Travel", "Adventure"],
    category: "Travel Adventures",
  },
  {
    id: 7,
    ownerId: 7,
    viewers: 120,
    title: "Coding Marathon",
    chats: [],
    startedTime: new Date(),
    tags: ["Technology", "Coding"],
    category: "Tech Talks",
  },
  {
    id: 8,
    ownerId: 8,
    viewers: 1000,
    title: "Epic Gaming Night",
    chats: [],
    startedTime: new Date(),
    tags: ["Gaming", "Entertainment"],
    category: "Gaming Fun",
  },
  {
    id: 9,
    ownerId: 9,
    viewers: 1000,
    title: "Epic Gaming Night",
    chats: [],
    startedTime: new Date(),
    tags: ["Gaming", "Entertainment"],
    category: "Gaming Fun",
  },
  {
    id: 10,
    ownerId: 10,
    viewers: 345,
    title: "Ace on day 27",
    chats: [],
    startedTime: new Date(),
    tags: ["English", "Troll"],
    category: "Troll VietNam",
  },
  {
    id: 11,
    ownerId: 11,
    viewers: 500,
    title: "Island Hopping Adventure",
    chats: [],
    startedTime: new Date(),
    tags: ["Travel", "Adventure"],
    category: "Travel Adventures",
  },
  {
    id: 12,
    ownerId: 12,
    viewers: 120,
    title: "Coding Marathon",
    chats: [],
    startedTime: new Date(),
    tags: ["Technology", "Coding"],
    category: "Tech Talks",
  },
  {
    id: 13,
    ownerId: 13,
    viewers: 1000,
    title: "Epic Gaming Night",
    chats: [],
    startedTime: new Date(),
    tags: ["Gaming", "Entertainment"],
    category: "Gaming Fun",
  },
];

//create fake user
const fakeUser: User = {
  id: 1,
  avatar: "",
  bio: "This is my bio",
  username: "MrBeast",
  email: "beast@gmail.com",
  birth: new Date(),
  phoneNumber: "02964827317",
  password: "",
};

//create fake channels base on streamings above
export const fakeChannels: Channel[] = [
  {
    id: 1,
    channelName: "MrBeast",
    streamKey: "",
    user: fakeUser,
    enableLLHLS: false,
    liveStreaming: false,
    tags: ["English", "Troll"],
    title: "Ace on day 27",
  },
  {
    id: 2,
    channelName: "NatureExplorer",
    streamKey: "",
    user: fakeUser,
    enableLLHLS: false,
    liveStreaming: false,
    tags: ["Travel", "Adventure"],
    title: "Island Hopping Adventure",
  },
  {
    id: 3,
    channelName: "CodeGeek",
    streamKey: "",
    user: fakeUser,
    enableLLHLS: false,
    liveStreaming: false,
    tags: ["Technology", "Coding"],
    title: "Coding Marathon",
  },
  {
    id: 4,
    channelName: "FoodExplorer",
    streamKey: "",
    user: fakeUser,
    enableLLHLS: false,
    liveStreaming: false,
    tags: ["Gaming", "Entertainment"],
    title: "Epic Gaming Night",
  },
  {
    id: 5,
    channelName: "ArtisticSoul",
    streamKey: "",
    user: fakeUser,
    enableLLHLS: false,
    liveStreaming: false,
    tags: ["English", "Troll"],
    title: "Ace on day 27",
  },
  {
    id: 6,
    channelName: "MusicHarmony",
    streamKey: "",
    user: fakeUser,
    enableLLHLS: false,
    liveStreaming: false,
    tags: ["Travel", "Adventure"],
    title: "Island Hopping Adventure",
  },
  {
    id: 7,
    channelName: "FitExplorer",
    streamKey: "",
    user: fakeUser,
    enableLLHLS: false,
    liveStreaming: false,
    tags: ["Technology", "Coding"],
    title: "Coding Marathon",
  },
  {
    id: 8,
    channelName: "BookWanderer",
    streamKey: "",
    user: fakeUser,
    enableLLHLS: false,
    liveStreaming: false,
    tags: ["Gaming", "Entertainment"],
    title: "Epic Gaming Night",
  },
  {
    id: 9,
    channelName: "MrBeast",
    streamKey: "",
    user: fakeUser,
    enableLLHLS: false,
    liveStreaming: false,
    tags: ["Gaming", "Entertainment"],
    title: "Epic Gaming Night",
  },
];

const channels = [
  {
    id: 1,
    ownerId: 1,
    category: "Troll VietNam",
    tags: ["English", "TrollVietNam"],
    description:
      "hi my name is jordy! nice to meet you :D. some things about me: i play 4 instruments, i like to draw, paint, and sing, and i have a dog named honey and cat named bee!",
    views: 1200000,
  },
  {
    id: 2,
    ownerId: 2,
    category: "Travel Adventures",
    tags: ["Travel", "Adventure"],
    description:
      "Exploring the world one destination at a time! Join me on thrilling adventures and discover hidden gems.",
    views: 850000,
  },
  {
    id: 3,
    ownerId: 3,
    category: "Tech Talks",
    tags: ["Technology", "Coding"],
    description:
      "Dive deep into the world of technology, coding, and innovation. Stay updated with the latest trends and developments.",
    views: 500000,
  },
  {
    id: 4,
    ownerId: 1,
    category: "Gaming Fun",
    tags: ["Gaming", "Entertainment"],
    description:
      "Get ready for exciting gaming sessions filled with laughter and epic moments. Let's have fun together!",
    views: 2000000,
  },
];

export { users, channels, streamings };
